# Site settings
title: Bio
baseurl: "/bio"
url: "https://garam-kim.github.io"
google_analytics: G-BRELYJ8ELX # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Garam Kim
  desc: Hello nice to meet you
  email: garam.kim@campus.tu-berlin.de
  selfie: assets/img/profile.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: garam-kim
  google_plus:
  instagram:
  keybase:
  linkedin: https://www.linkedin.com/in/garamkim1/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
